server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: ${db_host}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true

app:
  auth:
    tokenSecret: ${SECURITY_SECRET}
    tokenExpirationMSec: 864000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: https://nc-spring-2022.herokuapp.com
