server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: ${db_host}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
