server:
  port: 8080

spring:
  datasource:
    url: "${db_host}/nc"
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  auth:
    tokenSecret: ${SECURITY_SECRET}
    tokenExpirationMSec: 864000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080
